export enum Events {
  ACTION = 'action',
  OPEN = 'open',
  EDIT = 'edit',
  DELETE = 'delete',
  TOGGLE = 'toggle',
  FULL = 'full',
  COMPACT = 'compact',
  CLICK = 'click',
  CLOSE = 'close',
  SUBMIT = 'submit',
  CANCEL = 'cancel',
  UPDATE_MODEL_VALUE = 'update:modelValue',
  UPDATE_CATEGORY_VALUE = 'update:categoryValue',
  UPDATE_PRIORITY_VALUE = 'update:priorityValue',
  UPDATE_SORT_VALUE = 'update:sortValue',
  UPDATE_TITLE = 'update:title',
  UPDATE_DESCRIPTION = 'update:description',
  UPDATE_CATEGORY = 'update:category',
  UPDATE_PRIORITY = 'update:priority',
  UPDATE_DEADLINE = 'update:deadline',
  UPDATE_COMPLETED = 'update:completed'
}
